# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    exclude: "README.md"
  - id: end-of-file-fixer
  - id: debug-statements

- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.5.1
  hooks:
  # Update the uv lockfile
  - id: uv-lock